// Role definitions with permissions and navigation
export const ROLES = {
  directeur_general: {
    label: "Directeur Général",
    color: "from-slate-700 to-slate-900",
    textColor: "text-slate-800",
    bgColor: "bg-slate-100",
    icon: "👑",
    description: "Accès complet à tous les modules",
    pages: ["Dashboard", "Students", "Teachers", "Classes", "Subjects", "Staff", "Schedule", "Exams", "Grades", "Homework", "Resources", "Attendance", "Sanctions", "Messages", "Events", "Finance", "Bulletins", "SchoolYearManager", "MobileSaisie", "Pilotage"],
  },
  directeur_primaire: {
    label: "Directeur du Primaire",
    color: "from-blue-600 to-blue-800",
    textColor: "text-blue-800",
    bgColor: "bg-blue-100",
    icon: "🏫",
    description: "Gestion du cycle primaire",
    pages: ["Dashboard", "Students", "Teachers", "Classes", "Subjects", "Schedule", "Exams", "Grades", "Attendance", "Sanctions", "Messages", "Events", "Finance", "Bulletins", "Pilotage"],
  },
  directeur_college: {
    label: "Directeur du Collège",
    color: "from-indigo-600 to-indigo-800",
    textColor: "text-indigo-800",
    bgColor: "bg-indigo-100",
    icon: "🎓",
    description: "Gestion du cycle collège",
    pages: ["Dashboard", "Students", "Teachers", "Classes", "Subjects", "Schedule", "Exams", "Grades", "Attendance", "Sanctions", "Messages", "Events", "Finance", "Bulletins", "Pilotage"],
  },
  directeur_lycee: {
    label: "Directeur du Lycée",
    color: "from-violet-600 to-violet-800",
    textColor: "text-violet-800",
    bgColor: "bg-violet-100",
    icon: "🏛️",
    description: "Gestion du cycle lycée",
    pages: ["Dashboard", "Students", "Teachers", "Classes", "Subjects", "Schedule", "Exams", "Grades", "Attendance", "Sanctions", "Messages", "Events", "Finance", "Bulletins", "Pilotage"],
  },
  cpe: {
    label: "CPE",
    color: "from-orange-500 to-orange-700",
    textColor: "text-orange-700",
    bgColor: "bg-orange-100",
    icon: "👮",
    description: "Vie scolaire, discipline et présences",
    pages: ["Dashboard", "Students", "Attendance", "Sanctions", "Messages", "Events"],
  },
  enseignant: {
    label: "Enseignant",
    color: "from-green-600 to-green-800",
    textColor: "text-green-800",
    bgColor: "bg-green-100",
    icon: "📚",
    description: "Cours, notes, devoirs et ressources",
    pages: ["Dashboard", "Students", "Classes", "Schedule", "Exams", "Grades", "Homework", "Resources", "Attendance", "Messages", "MobileSaisie", "Pilotage"],
  },
  secretaire: {
    label: "Secrétaire",
    color: "from-cyan-600 to-cyan-800",
    textColor: "text-cyan-800",
    bgColor: "bg-cyan-100",
    icon: "📋",
    description: "Inscriptions, dossiers et administratif",
    pages: ["Dashboard", "Students", "Teachers", "Classes", "Staff", "Messages", "Events"],
  },
  comptable: {
    label: "Comptable",
    color: "from-teal-600 to-teal-800",
    textColor: "text-teal-800",
    bgColor: "bg-teal-100",
    icon: "💼",
    description: "Gestion RH et financière",
    pages: ["Dashboard", "Staff", "Teachers", "Messages", "Finance"],
  },
  eleve: {
    label: "Élève",
    color: "from-pink-500 to-pink-700",
    textColor: "text-pink-700",
    bgColor: "bg-pink-100",
    icon: "🎒",
    description: "Mes cours, notes, devoirs et planning",
    pages: ["Dashboard", "Schedule", "Grades", "Homework", "Resources", "Attendance", "Messages", "Events"],
  },
  parent: {
    label: "Parent",
    color: "from-amber-500 to-amber-700",
    textColor: "text-amber-700",
    bgColor: "bg-amber-100",
    icon: "👨‍👩‍👧",
    description: "Suivi scolaire de mon enfant",
    pages: ["Dashboard", "EspaceParent", "Pilotage", "Grades", "Attendance", "Homework", "Sanctions", "Messages", "Events"],
  },
};

export const PAGE_LABELS = {
  Dashboard: "Tableau de bord",
  Students: "Élèves",
  Teachers: "Enseignants",
  Classes: "Classes",
  Subjects: "Matières",
  Staff: "Personnel",
  Schedule: "Emploi du temps",
  Exams: "Examens",
  Grades: "Notes",
  Homework: "Devoirs",
  Resources: "Ressources",
  Attendance: "Présences",
  Sanctions: "Sanctions",
  Messages: "Messages",
  Events: "Événements",
  Pilotage: "Pilotage & Performance",
};