// Role definitions with permissions and navigation
export const ROLES = {
  admin_systeme: {
    label: "Administrateur Système",
    color: "from-red-600 to-rose-800",
    textColor: "text-red-800",
    bgColor: "bg-red-100",
    icon: "🔐",
    description: "Gestion des utilisateurs, rôles et configuration de l'application",
    pages: ["Dashboard", "Administration", "SchoolYearManager", "Rooms", "Visio", "Import", "OrgChart", "Tickets", "Cantine", "Tarifs"],
  },
  directeur_general: {
    label: "Directeur Général",
    color: "from-slate-700 to-slate-900",
    textColor: "text-slate-800",
    bgColor: "bg-slate-100",
    icon: "👑",
    description: "Accès complet à tous les modules",
    pages: ["Dashboard", "Students", "Teachers", "Classes", "Subjects", "Staff", "Schedule", "Rooms", "Exams", "Grades", "Moyennes", "Homework", "Resources", "Attendance", "Sanctions", "Messages", "Events", "Visio", "Finance", "Bulletins", "SchoolYearManager", "PassageDeClasse", "MobileSaisie", "Pilotage", "ProjectsScrum", "SocialNetwork", "Affectation", "AffectationEleves", "Import", "OrgChart", "Tickets", "Cantine", "AbsencesEnseignants", "Inscription", "Tarifs", "RHCollaborateurs", "RHConges", "RHTemps", "RHPaie", "Documents"],
  },
  directeur_primaire: {
    label: "Directeur du Primaire",
    color: "from-blue-600 to-blue-800",
    textColor: "text-blue-800",
    bgColor: "bg-blue-100",
    icon: "🏫",
    description: "Gestion du cycle primaire",
    pages: ["Dashboard", "Students", "Teachers", "Classes", "Subjects", "Schedule", "Rooms", "Exams", "Grades", "Moyennes", "Attendance", "Sanctions", "Messages", "Events", "Visio", "Finance", "Bulletins", "PassageDeClasse", "Pilotage", "ProjectsScrum", "SocialNetwork", "Affectation", "AffectationEleves", "Import", "OrgChart", "Tickets", "Cantine", "AbsencesEnseignants", "Inscription"],
  },
  directeur_college: {
    label: "Directeur du Collège",
    color: "from-indigo-600 to-indigo-800",
    textColor: "text-indigo-800",
    bgColor: "bg-indigo-100",
    icon: "🎓",
    description: "Gestion du cycle collège",
    pages: ["Dashboard", "Students", "Teachers", "Classes", "Subjects", "Schedule", "Rooms", "Exams", "Grades", "Moyennes", "Attendance", "Sanctions", "Messages", "Events", "Visio", "Finance", "Bulletins", "PassageDeClasse", "Pilotage", "ProjectsScrum", "SocialNetwork", "Import", "OrgChart", "Tickets", "Cantine", "AbsencesEnseignants", "Inscription"],
  },
  directeur_lycee: {
    label: "Directeur du Lycée",
    color: "from-violet-600 to-violet-800",
    textColor: "text-violet-800",
    bgColor: "bg-violet-100",
    icon: "🏛️",
    description: "Gestion du cycle lycée",
    pages: ["Dashboard", "Students", "Teachers", "Classes", "Subjects", "Schedule", "Rooms", "Exams", "Grades", "Moyennes", "Attendance", "Sanctions", "Messages", "Events", "Visio", "Finance", "Bulletins", "PassageDeClasse", "Pilotage", "ProjectsScrum", "SocialNetwork", "Affectation", "AffectationEleves", "Import", "OrgChart", "Tickets", "Cantine", "AbsencesEnseignants"],
  },
  cpe: {
    label: "CPE",
    color: "from-orange-500 to-orange-700",
    textColor: "text-orange-700",
    bgColor: "bg-orange-100",
    icon: "👮",
    description: "Vie scolaire, discipline et présences",
    pages: ["Dashboard", "Students", "Classes", "Schedule", "Exams", "Grades", "Moyennes", "Attendance", "Sanctions", "Messages", "Events", "Visio", "Pilotage", "SocialNetwork", "Tickets", "Cantine", "AbsencesEnseignants"],
  },
  enseignant: {
    label: "Enseignant",
    color: "from-green-600 to-green-800",
    textColor: "text-green-800",
    bgColor: "bg-green-100",
    icon: "📚",
    description: "Cours, notes, devoirs et ressources",
    pages: ["Dashboard", "Students", "Classes", "Subjects", "Schedule", "Exams", "Grades", "Moyennes", "Homework", "Resources", "Attendance", "Sanctions", "Messages", "Visio", "MobileSaisie", "Pilotage", "SocialNetwork", "Tickets", "Cantine", "AbsencesEnseignants"],
  },
  secretaire: {
    label: "Secrétaire",
    color: "from-cyan-600 to-cyan-800",
    textColor: "text-cyan-800",
    bgColor: "bg-cyan-100",
    icon: "📋",
    description: "Inscriptions, dossiers et administratif",
    pages: ["Dashboard", "Students", "Teachers", "Classes", "Subjects", "Staff", "Schedule", "Attendance", "Sanctions", "Messages", "Events", "Visio", "Finance", "Tickets", "Cantine", "AbsencesEnseignants", "Inscription"],
  },
  comptable: {
    label: "Comptable",
    color: "from-teal-600 to-teal-800",
    textColor: "text-teal-800",
    bgColor: "bg-teal-100",
    icon: "💼",
    description: "Gestion RH et financière",
    pages: ["Dashboard", "Staff", "Teachers", "Messages", "Finance", "Tickets", "RHCollaborateurs", "RHTemps", "RHPaie"],
  },
  rh_manager: {
    label: "Responsable RH",
    color: "from-purple-600 to-purple-800",
    textColor: "text-purple-800",
    bgColor: "bg-purple-100",
    icon: "👥",
    description: "Gestion des contrats, congés, temps de travail et paie",
    pages: ["Dashboard", "Teachers", "Staff", "Schedule", "AbsencesEnseignants", "Messages", "Tickets", "RHCollaborateurs", "RHConges", "RHTemps", "RHPaie"],
  },
  eleve: {
    label: "Élève",
    color: "from-pink-500 to-pink-700",
    textColor: "text-pink-700",
    bgColor: "bg-pink-100",
    icon: "🎒",
    description: "Mes cours, notes, devoirs et planning",
    pages: ["Dashboard", "StudentDashboard", "Grades", "Schedule", "Homework", "Resources", "Messages", "Events", "Visio", "SocialNetwork", "Cantine", "Documents"],
  },
  parent: {
    label: "Parent",
    color: "from-amber-500 to-amber-700",
    textColor: "text-amber-700",
    bgColor: "bg-amber-100",
    icon: "👨‍👩‍👧",
    description: "Suivi scolaire de mon enfant",
    pages: ["Dashboard", "EspaceParent", "Grades", "Attendance", "Homework", "Sanctions", "Finance", "Messages", "Events", "Visio", "SocialNetwork", "Pilotage", "Cantine", "Documents"],
  },
};

export const PAGE_LABELS = {
  Dashboard: "Tableau de bord",
  Students: "Élèves",
  Teachers: "Enseignants",
  Classes: "Classes",
  Subjects: "Matières",
  Staff: "Personnel",
  Schedule: "Emploi du temps",
  Rooms: "Salles & Infrastructures",
  Exams: "Examens & Notes",
  Grades: "Notes",
  Moyennes: "Calculs & Moyennes",
  Homework: "Devoirs",
  Resources: "Ressources",
  Attendance: "Présences",
  Sanctions: "Sanctions",
  Messages: "Messages",
  Events: "Événements",
  Visio: "Visioconférence",
  Finance: "Finance & Contentieux",
  Bulletins: "Bulletins Scolaires",
  SchoolYearManager: "Années Scolaires",
  PassageDeClasse: "Passage de Classe",
  MobileSaisie: "Saisie Rapide Mobile",
  EspaceParent: "Espace Parents Premium",
  Pilotage: "Pilotage & Performance",
  ProjectsScrum: "Projets Agile / Scrum",
  SocialNetwork: "Réseau Social Éducatif",
  Affectation: "Affectation Intelligente",
  AffectationEleves: "Affectation Élèves",
  StudentDashboard: "Mon Espace Élève",
  Administration: "Administration Système",
  Import: "Import de données",
  OrgChart: "Organigramme",
  Tickets: "Demandes Internes",
  Cantine: "Cantine Scolaire",
  AbsencesEnseignants: "Absences Enseignants",
  Inscription: "Inscriptions & Onboarding",
  Tarifs: "Grille Tarifaire",
  Documents: "Mes Documents",
  RHCollaborateurs: "Collaborateurs RH",
  RHConges: "Congés & Absences",
  RHTemps: "Temps de Travail",
  RHPaie: "Paie",
};

// All pages grouped by category (for the permissions matrix UI)
export const ALL_PAGES_BY_CATEGORY = [
  {
    category: "Général",
    icon: "🏠",
    pages: [
      { key: "Dashboard", label: "Tableau de bord" },
    ],
  },
  {
    category: "Pédagogie",
    icon: "📚",
    pages: [
      { key: "Students", label: "Élèves" },
      { key: "Inscription", label: "Inscriptions & Onboarding" },
      { key: "Teachers", label: "Enseignants" },
      { key: "Classes", label: "Classes" },
      { key: "Subjects", label: "Matières" },
      { key: "Schedule", label: "Emploi du temps" },
      { key: "Rooms", label: "Salles & Infrastructures" },
      { key: "Exams", label: "Examens & Notes" },
      { key: "Grades", label: "Notes" },
      { key: "Moyennes", label: "Calculs & Moyennes" },
      { key: "Homework", label: "Devoirs" },
      { key: "Resources", label: "Ressources" },
      { key: "Bulletins", label: "Bulletins Scolaires" },
    ],
  },
  {
    category: "Vie scolaire",
    icon: "🏫",
    pages: [
      { key: "Attendance", label: "Présences" },
      { key: "Sanctions", label: "Sanctions" },
      { key: "Messages", label: "Messages" },
      { key: "Events", label: "Événements" },
      { key: "Visio", label: "Visioconférence" },
      { key: "Cantine", label: "Cantine Scolaire" },
      { key: "AbsencesEnseignants", label: "Absences Enseignants" },
    ],
  },
  {
    category: "Ressources Humaines",
    icon: "👥",
    pages: [
      { key: "RHCollaborateurs", label: "Collaborateurs RH" },
      { key: "RHConges",         label: "Congés & Absences" },
      { key: "RHTemps",          label: "Temps de Travail" },
      { key: "RHPaie",           label: "Paie" },
    ],
  },
  {
    category: "Administration",
    icon: "🏢",
    pages: [
      { key: "Staff", label: "Personnel" },
      { key: "Finance", label: "Finance & Contentieux" },
      { key: "SchoolYearManager", label: "Années Scolaires" },
      { key: "PassageDeClasse", label: "Passage de Classe" },
    ],
  },
  {
    category: "Espaces dédiés",
    icon: "👤",
    pages: [
      { key: "EspaceParent", label: "Espace Parents Premium" },
      { key: "StudentDashboard", label: "Mon Espace Élève" },
      { key: "MobileSaisie", label: "Saisie Rapide Mobile" },
    ],
  },
  {
    category: "Outils avancés",
    icon: "⚙️",
    pages: [
      { key: "Pilotage", label: "Pilotage & Performance" },
      { key: "ProjectsScrum", label: "Projets Agile / Scrum" },
      { key: "SocialNetwork", label: "Réseau Social Éducatif" },
      { key: "Affectation", label: "Affectation Intelligente" },
      { key: "AffectationEleves", label: "Affectation Élèves" },
    ],
  },
  {
    category: "Système",
    icon: "🔐",
    pages: [
      { key: "Administration", label: "Administration Système" },
      { key: "Tarifs", label: "Grille Tarifaire" },
      { key: "Import", label: "Import de données" },
      { key: "OrgChart", label: "Organigramme" },
    ],
  },
];